using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace DestinyRanger.EditorTools
{
    [InitializeOnLoad]
    public static class FateWeaverDeferredIntegrationRunner
    {
        private const string RequestPath = "Temp/FateWeaverRunIntegrationBuild.request";
        private const string ReportPath = "Assets/DestinyRanger/Docs/UNITY_DEFERRED_RUN_REPORT.md";
        private static bool running;
        private static double nextPollTime;

        static FateWeaverDeferredIntegrationRunner()
        {
            EditorApplication.delayCall += RunIfRequested;
            EditorApplication.update += PollForRequestMarker;
        }

        [MenuItem("Destiny Ranger/Fate Weaver/Run Deferred Integration Now")]
        public static void RunFromMenu()
        {
            if (!EditorIsIdle())
            {
                WriteReport("waiting", "Unity Editor is compiling, updating assets, playing, or about to change Play Mode. Leave Play Mode and run the menu again, or keep the request marker in place for automatic retry.");
                Debug.LogWarning("Fate Weaver integration did not run because the editor is not idle.");
                return;
            }

            RunIntegration("manual-menu", deleteRequestMarker: false);
        }

        private static void RunIfRequested()
        {
            if (!CanRunNow())
                return;

            RunIntegration("request-marker", deleteRequestMarker: true);
        }

        private static void PollForRequestMarker()
        {
            if (EditorApplication.timeSinceStartup < nextPollTime)
                return;

            nextPollTime = EditorApplication.timeSinceStartup + 1.0d;
            RunIfRequested();
        }

        private static bool CanRunNow()
        {
            if (running || !File.Exists(RequestPath))
                return false;

            if (!EditorIsIdle())
                return false;

            return true;
        }

        private static bool EditorIsIdle()
        {
            return !EditorApplication.isCompiling
                && !EditorApplication.isUpdating
                && !EditorApplication.isPlaying
                && !EditorApplication.isPlayingOrWillChangePlaymode;
        }

        private static void RunIntegration(string trigger, bool deleteRequestMarker)
        {
            running = true;
            try
            {
                FateWeaverPrefabBuilder.BuildIntegrationPrefabsAndScenes();
                FateWeaverDeliveryValidator.ValidateBuiltIntegration();
                FateWeaverDeliveryValidator.ValidateFullDelivery();
                WriteReport("complete", "Deferred Unity integration build and validation completed inside the open Unity Editor. Trigger: " + trigger);
                Debug.Log("Fate Weaver deferred integration build completed.");
            }
            catch (Exception ex)
            {
                WriteReport("failed", ex.ToString());
                Debug.LogException(ex);
            }
            finally
            {
                if (deleteRequestMarker)
                {
                    try
                    {
                        File.Delete(RequestPath);
                    }
                    catch (Exception ex)
                    {
                        Debug.LogWarning("Could not delete Fate Weaver deferred request marker: " + ex.Message);
                    }
                }

                AssetDatabase.Refresh();
                running = false;
            }
        }

        private static void WriteReport(string status, string detail)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ReportPath));
            File.WriteAllText(ReportPath, "# Fate Weaver Unity Deferred Run Report\n\n"
                + "- Status: `" + status + "`\n"
                + "- Request marker: `" + RequestPath + "`\n"
                + "- Generated by: `FateWeaverDeferredIntegrationRunner`\n\n"
                + "## Detail\n\n"
                + "```text\n" + detail + "\n```\n", System.Text.Encoding.UTF8);
        }
    }
}
