using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

namespace BubuTown.EditorTools
{
    public static class BubuTownUrpProjectConfigurator
    {
        private const string SettingsFolder = "Assets/BubuTown/Settings";
        private const string RendererAssetPath = SettingsFolder + "/BubuTown_URP_Renderer.asset";
        private const string PipelineAssetPath = SettingsFolder + "/BubuTown_URP_Asset.asset";
        private const string ReportPath = "Assets/BubuTown/Docs/UrpProjectConfigurationReport.md";

        [MenuItem("BubuTown/Configure Unity 6 URP Project")]
        public static void ConfigureUnity6UrpProject()
        {
            Directory.CreateDirectory(SettingsFolder);

            var rendererData = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererAssetPath);
            if (rendererData == null)
            {
                rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
                AssetDatabase.CreateAsset(rendererData, RendererAssetPath);
            }

            var pipelineAsset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(PipelineAssetPath);
            if (pipelineAsset == null)
            {
                pipelineAsset = UniversalRenderPipelineAsset.Create(rendererData);
                AssetDatabase.CreateAsset(pipelineAsset, PipelineAssetPath);
            }

            pipelineAsset.renderScale = 1f;
            pipelineAsset.msaaSampleCount = 4;
            pipelineAsset.supportsHDR = true;
            pipelineAsset.shadowDistance = 85f;

            GraphicsSettings.defaultRenderPipeline = pipelineAsset;
            QualitySettings.renderPipeline = pipelineAsset;

            EditorUtility.SetDirty(rendererData);
            EditorUtility.SetDirty(pipelineAsset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            WriteReport(pipelineAsset, rendererData);
            Debug.Log("[BubuTown] Unity 6 URP project configuration applied: " + PipelineAssetPath);
        }

        private static void WriteReport(UniversalRenderPipelineAsset pipelineAsset, UniversalRendererData rendererData)
        {
            var report = new StringBuilder();
            report.AppendLine("# URP Project Configuration Report");
            report.AppendLine();
            report.AppendLine("Generated by `BubuTownUrpProjectConfigurator` to keep the Unity 6.3 prototype aligned with URP-friendly imported city assets.");
            report.AppendLine();
            report.AppendLine("## Summary");
            report.AppendLine();
            report.AppendLine("- Universal RP package target: `com.unity.render-pipelines.universal` 17.3.0");
            report.AppendLine("- URP asset: `" + AssetDatabase.GetAssetPath(pipelineAsset) + "`");
            report.AppendLine("- Renderer data: `" + AssetDatabase.GetAssetPath(rendererData) + "`");
            report.AppendLine("- GraphicsSettings.defaultRenderPipeline: " + Gate(GraphicsSettings.defaultRenderPipeline == pipelineAsset));
            report.AppendLine("- QualitySettings.renderPipeline: " + Gate(QualitySettings.renderPipeline == pipelineAsset));
            report.AppendLine("- Render scale: " + pipelineAsset.renderScale.ToString("0.##"));
            report.AppendLine("- MSAA samples: " + pipelineAsset.msaaSampleCount);
            report.AppendLine("- HDR: " + Gate(pipelineAsset.supportsHDR));
            report.AppendLine("- Shadow distance: " + pipelineAsset.shadowDistance.ToString("0.#"));
            report.AppendLine();
            report.AppendLine("## Current Gate");
            report.AppendLine();
            report.AppendLine(GraphicsSettings.defaultRenderPipeline == pipelineAsset && QualitySettings.renderPipeline == pipelineAsset
                ? "PASS: project-level render pipeline settings now point at the Bubu Town URP asset."
                : "CHECK: render pipeline assignment is incomplete.");

            Directory.CreateDirectory(Path.GetDirectoryName(ReportPath));
            File.WriteAllText(ReportPath, report.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(ReportPath);
        }

        private static string Gate(bool passed)
        {
            return passed ? "PASS" : "CHECK";
        }
    }
}
